import { StyleSheet, Platform } from "react-native";
const OS = Platform.OS;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#162529",
    paddingLeft: 24,
    paddingRight: 24,
  },
  bodyContainer: {
    flex: 1,
    marginTop: 43,
  },
  playBtn: {
    height: 30,
    width: 90,
    backgroundColor: "#b23b3b",
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center", 
    paddingLeft: 10,
    paddingRight: 10,
    marginTop: 10,
  },
  playBtnText: {
    fontFamily: "medium",
    color: "#28282B",
    fontSize: 16,
  },
  infoContainer: {
    marginTop: "18%",
    alignItems: "center",
  },
  nameText: {
    fontFamily: "displayMedium",
    fontSize: 24,
    color: "#FFF",
  },
  despContainer: {
    flexDirection: "row",
    marginTop: 8,
  },
  despText: {
    fontFamily: "displayMedium",
    fontSize: 20,
    color: "#FFF",
  },
  expLevel: {
    fontFamily: "displayMedium",
    fontSize: 20,
    color: "#D5FF45",
  },
  actionsContainer: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    marginTop: "10%",
  },
  historyBtn: {
    backgroundColor: "#162529",
    borderColor: "#636363",
    borderWidth: 1,
    padding: 8,
    paddingLeft: 20,
    paddingRight: 20,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  historyBtn3: {
    backgroundColor: "#162529",
    borderColor: "#636363",
    borderWidth: 1,
    padding: 10,
    paddingLeft: 20,
    paddingRight: 20,
    borderRadius: 8,
    marginLeft: 15,
    marginRight: 15,
    justifyContent: "center",
    alignItems: "center",
  },
  friendsBtn: {
    backgroundColor: "#162529",
    borderColor: "#636363",
    borderWidth: 1,
    padding: 9.8,
    borderRadius: 8,
    marginLeft: 15,
    marginRight: 15,
    paddingLeft: 24,
    paddingRight: 24,
  },
  editBtn: {
    marginLeft: 6.5,
    marginRight: 6.5,
  },
  historyBtn2: {
    height: 50,
    width: 90,
    backgroundColor: "#162529",
    borderColor: "#DC143C",
    borderWidth: 2,
    padding: 10.5,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  historyBtnText: {
    fontFamily: "medium",
    fontSize: 18,
    color: "#FFF",
  },
  dots: {
    padding: 10.5,
  },
  friendsBtnText: {
    fontFamily: "medium",
    fontSize: 16,
    color: "#FFF",
  },
  bioContainer: {
    alignItems: "center",
    marginTop: "12%",
    paddingHorizontal: 32,
  },
  bioText: {
    fontFamily: "medium",
    fontSize: 16,
    color: "#FFF",
    textAlign: "center",
  },
  cardsContainer: {
    justifyContent: "center",
    marginTop: OS == "android" ? "0%" : "20%",
    flexDirection: "row",
  },
  card: {
    height: 120,
    width: 120,
    justifyContent: "flex-end",
  },
  cardText: {
    fontFamily: "medium",
    fontSize: 10,
    color: "#FFF",
    textShadowColor: "#000",
    marginBottom: 2,
    
  },
  cardImage: {
    height: 63,
    width: 63,
    marginTop: 10,
    borderRadius: 117,
  },
  dropdownContainer: {
    borderWidth: 1,
    borderColor: "#636363",
    borderRadius: 16,
    marginTop: -4,
    backgroundColor: "#162529",
    marginBottom: 16,
    height: 50,
  },
  dropdownText: {
    fontFamily: "medium",
    fontSize: 24,
    color: "grey",
    marginLeft: 12,
  },
  dropdownDataContainer: {
    borderWidth: 1,
    borderColor: "#636363",
    borderRadius: 4,
    zIndex: 1000,
    backgroundColor: "#162529",
    color: "#EEE",
  },
});
export default styles;
